name: vercel-from-workflow-run

inputs:
  artifact: 
    description: 'The name of the artifact to deploy to Vercel'
    required: true
  artifact-zip-name:
    required: false
    description: 'The name of the zip file in the artifact (omit if you do not store a zip INSIDE your artifact).'
  vercel-token:
    required: true
    description: "A secret representing the used Vercel Token"
  vercel-org:
    required: true
    description: "A secret representing the used Vercel Organization"
  vercel-project-id:
    required: true
    description: "A secret representing the used Vercel Project ID"
  ng-version:
    description: "Your Angular Version"
    required: false
    default: '19'

outputs:
  url:
    description: "The Vercel URL for the deployment"
    value: ${{ steps.vercel-deploy.outputs.url }}
    
runs:
  using: 'composite'
  steps:
  - name: 'Download ${{ inputs.artifact }}'
    uses: actions/github-script@v7
    with:
      script: |
        var artifacts = await github.actions.listWorkflowRunArtifacts({
          owner: context.repo.owner,
          repo: context.repo.repo,
          run_id: ${{ github.event.workflow_run.id }},
        });
        var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
          return artifact.name == "${{ inputs.artifact }}"
        })[0];
        var download = await github.actions.downloadArtifact({
          owner: context.repo.owner,
          repo: context.repo.repo,
          artifact_id: matchArtifact.id,
          archive_format: 'zip',
        });
        var fs = require('fs');
        fs.writeFileSync('${{github.workspace}}/${{ inputs.artifact }}.zip', Buffer.from(download.data))
        
  - run: unzip -q ${{ inputs.artifact }}.zip -d . && rm ${{ inputs.artifact }}.zip
    name: Unzip {{ inputs.artifact }}.zip
    shell: bash

  - run: unzip -q ${{ inputs.artifact-zip-name }} -d . && rm ${{ inputs.artifact-zip-name }}
    name: Unzip ${{ inputs.artifact-zip-name }}
    shell: bash

  - uses: graycoreio/github-actions/angular-universal-vercel@main
    id: vercel-deploy
    with:
      vercel_token: ${{ inputs.vercel-token }}
      vercel_org: ${{ inputs.vercel-org }}
      vercel_project_id: ${{ inputs.vercel-project-id }}
      ng_version: ${{ inputs.ng-version }}
