name: "Set Package Versions from Root"
author: "Graycore"
description: "A Github Action that sets package dependency versions from versions defined in the root of the monorepo."

inputs:
  root-package-path:
    required: false
    description: "The path to a package.json"
    default: './package.json'
  package-glob:
    required: false
    description: "A glob pattern specifying the package.json's that you want to modify."
    default: 'dist/**/package.json'
  placeholder:
    required: false
    description: "The value that of a key that holds a version that needs to be replaced."
    default: '0.0.0-PLACEHOLDER'

runs:
  using: "node20"
  main: dist/index.js

branding:
  icon: "code"
  color: "green"
