name: "Angular Universal Vercel Deploy"

author: "Graycore"

description: "A Github Action that deploys an Angular Universal application to Vercel"

inputs:
  prod:
    description: "Whether or not to do a Vercel Prod Deploy"
    required: false
    default: 'false'
  vercel_token:
    description: "Your Vercel Token"
    required: true
  vercel_org:
    description: "Your Vercel Org"
    required: true
  vercel_project_id:
    description: "Your Vercel Project Id"
    required: true
  ng_version:
    description: "Your Angular Version"
    required: false
    default: '19'
  ng_ssr_engine:
    description: "Which version of the Angular's SSR engine that you're using. One of 'CommonEngine' or 'AngularNodeAppEngine'"
    required: false
    default: 'CommonEngine'

outputs:
  url: 
    description: 'The URL of the Vercel Deployment'

runs:
  using: "docker"
  image: "docker://graycore/angular-universal-vercel:latest"

branding:
  icon: "code"
  color: "green"
