name: LHCI Test

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Test LHCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./lighthouse-ci