name: LHCI Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test LHCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - uses: ./lighthouse-ci
        with:
          domain: https://www.example.com
          config_path: .github/workflows/lhci/.lighthouserc.js